### ISSUE TITLE
ExtractorTest with jasmine seems to hang

### ISSUE THREAD

**Issue by quyin** [ecologylab/NewBigSemantics#8]
when I run the test using `gulp` and then `gulp test`, the program seems to hang there forever.

`phantomjs` process is confirmed running, even the tests already finished.

seems a control flow issue.

**Comment by teschty** [comment]
Yeah, the problem is that unfortunately Jasmine does not appear to have a way to run code after _all_ tests complete, only after each test suite completes, or after each test completes. I haven't completely looked into it, but I was thinking for now of just putting code in the last test suite to close phantom, which isn't exactly very nice but will work.

**Comment by quyin** [comment]
thanks for the information.

alternative solution would be to kill phantomjs at the end of each test case, and respawn a new one when starting the next test case. in some cases this would be preferable, because it further isolates each test case. what do you think?

**Comment by teschty** [comment]
That seems like a good solution, only bad thing I can think of is that it would spam the console quite a bit but that's not really a problem. 

And further isolation would probably be better, so it good to me!

**Comment by quyin** [comment]
after we have some logging facilities, we can redirect all the phantomjs output into a log file. so I'm not too worried about the console output right now.
